In [2]:
# 公里換英里
# 迴圈

dist_in_km = [3, 5, 10, 21.1, 42.195]
dist_in_mile = []

for d in dist_in_km:
  dist_in_mile.append(d * 0.62137)

print(dist_in_mile)

[1.86411, 3.1068499999999997, 6.213699999999999, 13.110907000000001, 26.21870715]


In [3]:
# arrary 處理

dist_in_km = [3, 5, 10, 21.1, 42.195]
dist_in_mile = [d * 0.62137 for d in dist_in_km]
print(dist_in_mile)

[1.86411, 3.1068499999999997, 6.213699999999999, 13.110907000000001, 26.21870715]


In [4]:
# lambda expression 與 map() 函數

dist_in_km = [3, 5, 10, 21.1, 42.195]
dist_in_mile = list(map(lambda d : d * 0.62137, dist_in_km))
print(dist_in_mile)

[1.86411, 3.1068499999999997, 6.213699999999999, 13.110907000000001, 26.21870715]


In [5]:
# NumPy to the Rescue
# NumPy，全名為 Numerical Python 創建一種稱為 ndarray 的型別

import numpy as np

dist_in_km = [3, 5, 10, 21.1, 42.195]
dist_in_km = np.array(dist_in_km)
dist_in_mile = dist_in_km * 0.62137
print(dist_in_mile)

[ 1.86411     3.10685     6.2137     13.110907   26.21870715]


In [7]:
# np.array() ：將原生 list 轉換為 ndarray

dist_in_km = [3, 5, 10, 21.1, 42.195]
print(type(dist_in_km))

dist_in_km = np.array(dist_in_km)
print(type(dist_in_km))

<class 'list'>
<class 'numpy.ndarray'>


In [13]:
# np.arange(low, high, by) ：與 range() 函數用法相同，只是產出的 iterable 型別為 ndarray 而非原生 list

print(np.arange(8)) # high 不包含
print(np.arange(1, 8)) # low 包含、high 不包含
print(np.arange(1, 10, 2))

range(0, 8)
[0 1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[1 3 5 7 9]


In [21]:
# np.linspace(start, stop, num, dtype) ：在介於 start（包含）與 stop（包含）之間產生長度為 num 的 ndarray 由於是等距間隔故預設的型別設為浮點數，但是不用擔心，型別可以自由調整

arr = np.linspace(1, 10, 10)
print(arr)
print(arr.dtype)
print("\n")
arr = arr.astype(int)
print(arr)
print(arr.dtype)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


[ 1  2  3  4  5  6  7  8  9 10]
int32


In [20]:
# ndarray 的特質 :與原生 list 很不同的特性就是一個 ndarray 中僅能儲存單一種型別

lst = [42.195, 'km', True]

for i in lst:
  print(type(i))

print(lst)

arr = np.array(lst)

for i in arr:
  print(type(i))
  
print(lst)

<class 'float'>
<class 'str'>
<class 'bool'>
[42.195, 'km', True]


<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
['42.195' 'km' 'True']


In [32]:
# 利用 .reshape 方法建立不同維度 ndarray

# 維度 0：純量（scalar）

my_scalar = 87
print(my_scalar)

87


In [36]:
# 維度 1：向量（vector）: 向量是一個欄（column）or 列（row）的純量集合
# # column vector vs row vector

print("column vector　欄向量 mx1 :\n")
uc = np.array([8, 7]).reshape(2, 1)
vc = np.array([8, 7, 6]).reshape(3, 1)
print(uc)
print("\n")
print(vc)

print("\n")
print("row vector　列向量 1xn :\n")

ur = np.array([8, 7]).reshape(1, 2)
vr = np.array([8, 7, 6]).reshape(1, 3)
print(ur)
print("\n")
print(vr)

column vector　欄向量 mx1 :

[[8]
 [7]]


[[8]
 [7]
 [6]]


row vector　列向量 1xn :

[[8 7]]


[[8 7 6]]


In [37]:
# 維度 2：矩陣（matrix）
# 矩陣是兩個維度，列與欄的純量集合，我們習慣稱一個矩陣的外觀為 m x n，意思是有 m 個列（rows）n 個欄（columns）

my_mat = np.arange(1, 13).reshape(4, 3) # 4 x 3 的矩陣
print(my_mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
# 維度 3：張量（tensor）

# 張量是三個維度的純量集合，張量的外觀如果為 (2, 4, 3) 可以想成有 2 個 4 x 3 的矩陣疊合

my_tensor = np.arange(1, 25).reshape(2, 4, 3)
print(my_tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]
