In [1]:
# Matrix 或 ndarray？
# 矩陣指的是外觀為 m x n 的二維資料，位於矩陣中的元素則以 ij 表示

import numpy as np

A = np.array([
    [1+1, 1+2, 1+3, 1+4],
    [2+1, 2+2, 2+3, 2+4],
    [3+1, 3+2, 3+3, 3+4]
])
print(A)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [2]:
A = np.mat([
    [1+1, 1+2, 1+3, 1+4],
    [2+1, 2+2, 2+3, 2+4],
    [3+1, 3+2, 3+3, 3+4]
])

B = np.array([
    [1+1, 1+2, 1+3, 1+4],
    [2+1, 2+2, 2+3, 2+4],
    [3+1, 3+2, 3+3, 3+4]
])
print(A)
print(type(A))
print("------")
print(B)
print(type(B))

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
<class 'numpy.matrix'>
------
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
<class 'numpy.ndarray'>


In [7]:
# 使用 ndarray！因為有著以下幾個優點：
# 能夠表示向量、矩陣與張量
# 許多 NumPy 的函數輸出型別為 ndarray 而非 matrix
# ndarray 進行元素級別運算與線性代數運算時使用的運算符號有明顯區隔

# 矩陣與矩陣的加減
# 矩陣的加法具有交換律，而減法不具有交換律

J = np.array([
    [12, 23, 14],
    [20, 29, 38],
    [3, 6, 10],
    [15, 15, 2]
])

F = np.array([
    [13, 33, 22],
    [10, 19, 8],
    [30, 0, 20],
    [0, 0, 0]
])

print(J+F)
print(F+J)
print(np.array_equal(J + F, F + J))

print("\n")

print(J-F)
print(F-J)
print(np.array_equal(J - F, F - J))

[[25 56 36]
 [30 48 46]
 [33  6 30]
 [15 15  2]]
[[25 56 36]
 [30 48 46]
 [33  6 30]
 [15 15  2]]
True


[[ -1 -10  -8]
 [ 10  10  30]
 [-27   6 -10]
 [ 15  15   2]]
[[  1  10   8]
 [-10 -10 -30]
 [ 27  -6  10]
 [-15 -15  -2]]
False


In [10]:
# 矩陣的加法與減法具有結合律。

A = np.array([
    [5, 3],
    [0, 1]
])

B = np.array([
    [4, -1],
    [2, 3]
])

C = np.array([
    [9, 8],
    [-6, 2]
])

print((A+B)+C)
print(A+(B+C))
print(np.array_equal((A+B)+C, A+(B+C)))

[[18 10]
 [-4  6]]
[[18 10]
 [-4  6]]
True


In [11]:
# 矩陣與純量相乘

# 矩陣 A 與純量 k 相乘即將所有的 aij 都乘上 k

A = np.array([
    [2, -3, -4, 0],
    [-3, 1, -1, 5],
    [4, 0, -6, -7]
])

k = -4

print(k * A)

[[ -8  12  16   0]
 [ 12  -4   4 -20]
 [-16   0  24  28]]


In [15]:
# 並非任意兩個矩陣都能夠相乘，如果矩陣 A 的外觀為 m x n、矩陣 B 的外觀為 p x q，n 與 p 要相等， A * B 才能夠運算，A * B 的外觀為 m x q

C = np.array([
    [4, -3, 2],
    [0, 1, -1],
    [5, 4, 0]
])

D = np.array([
    [2, 2, -5],
    [3, 1, 0],
    [-1, 1, 4]
])

print(C.dot(D))

[[ -3   7 -12]
 [  4   0  -4]
 [ 22  14 -25]]


In [17]:
# 多數的情況下，矩陣與矩陣相乘時不具有交換律。

print(C.dot(D))
print(D.dot(C))
print(np.array_equal(C.dot(D), D.dot(C)))

[[ -3   7 -12]
 [  4   0  -4]
 [ 22  14 -25]]
[[-17 -24   2]
 [ 12  -8   5]
 [ 16  20  -3]]
False


In [20]:
# 矩陣相乘具有結合律。

A = np.array([
    [4, -1],
    [2, 3]
])

B = np.array([
    [5, 3],
    [0, 1]
])

C = np.array([
    [9, 8],
    [-6, 2]
])

D = (A.dot(B)).dot(C)
E = A.dot(B.dot(C))

print(D)
print(E)
print(np.array_equal(D, E))

[[114 182]
 [ 36  98]]
[[114 182]
 [ 36  98]]
True


In [22]:
# 矩陣相乘具有分配律。

D = A.dot(B + C)
E = A.dot(B) + A.dot(C)

print(D)
print(E)
print(np.array_equal(D, E))

[[62 41]
 [10 31]]
[[62 41]
 [10 31]]
True


In [23]:
# 特殊的矩陣

# 單位矩陣（Identity Matrix）：以大寫英文字母 I 表示，NumPy 建立單位矩陣的方法是 np.eye() 取 I 與 Eye 諧音。是對角線上為 1 其餘位置為 0 的矩陣。

print(np.eye(2, dtype = 'int')) # 2 x 2 的單位矩陣
print(np.eye(3, dtype = 'int')) # 3 x 3 的單位矩陣
print(np.eye(4, dtype = 'int')) # 4 x 4 的單位矩陣

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [25]:
# 矩陣與矩陣相乘在特殊情況下具有交換律，矩陣與單位矩陣相乘就符合這個情況。

C = np.array([
    [4, -3, 2],
    [0, 1, -1],
    [5, 4, 0]
])

D = np.eye(3, dtype=int)

print(C.dot(D))
print(D.dot(C))
print(np.array_equal(C.dot(D), D.dot(C)))

[[ 4 -3  2]
 [ 0  1 -1]
 [ 5  4  0]]
[[ 4 -3  2]
 [ 0  1 -1]
 [ 5  4  0]]
True


In [28]:
# 轉置矩陣（Transpose）：將矩陣 A 中每個數字從 (m, n) 的位置轉換到 (n, m) 後所呈現的矩陣 B 即稱為矩陣 A 的轉置矩陣，NumPy 建立轉置矩陣是使用 ndarray 的 .T 屬性

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = A.T

print(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [32]:
# 矩陣 A 與矩陣 B 相加後轉置，與先轉置矩陣 A 與矩陣 B 後再相加是相同的。

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

C = (A + B).T
D = A.T + B.T

print(C)
print(D)
print(np.array_equal(C, D))

[[ 8 12 16]
 [10 14 18]]
[[ 8 12 16]
 [10 14 18]]
True


In [33]:
# 矩陣 A 與矩陣 B 相乘後轉置，與矩陣 B 轉置再乘矩陣 A 轉置的結果相同。

A = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

B = np.array([
    [1, 0, 2],
    [4, 5, 6]
])

C = (A.dot(B)).T
D = (B.T).dot(A.T)

print(C)
print(D)
print(np.array_equal(C, D))

[[ 9 19 29]
 [10 20 30]
 [14 30 46]]
[[ 9 19 29]
 [10 20 30]
 [14 30 46]]
True


In [36]:
# 反矩陣（Inverse）：如果矩陣 M 是一個可逆矩陣（invertible），則矩陣 M 與其反矩陣相乘之後可以得到一個單位矩陣

# NumPy 使用 np.linalg.inv() 函數可以計算反矩陣

A = np.array([
    [4, -7],
    [2, -3]
])

A_inv = np.linalg.inv(A)

print(A)
print(A_inv)
print(A.dot(A_inv))

[[ 4 -7]
 [ 2 -3]]
[[-1.5  3.5]
 [-1.   2. ]]
[[1. 0.]
 [0. 1.]]


In [48]:
# 並不是每個矩陣都具有反矩陣，以前述 2 x 2 的矩陣 M 為例，當 ad-bc 為零的時候，矩陣 M 就稱為不可逆（singular）矩陣，呼叫 np.linalg.inv() 會產生錯誤：

B = np.array([
    [8, 2],
    [12, 3]
])

print('矩陣 B 是不可逆矩陣 8x3=2x12')

B_inv = np.linalg.inv(B)
print(B.dot(B_inv))

print('矩陣 B 與其反矩陣相乘之後不是一個單位矩陣')

矩陣 B 是不可逆矩陣 8x3=2x12
[[0. 0.]
 [0. 0.]]
矩陣 B 與其反矩陣相乘之後不是一個單位矩陣
